# Generated by Django 5.2.3 on 2025-07-07 10:26

import cinema_up_project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema_up_project", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="performance",
            options={"ordering": ["-show_time"]},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=cinema_up_project.models.play_image_upload_path,
            ),
        ),
    ]
